/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as LoginAlunoRouteImport } from './routes/login.aluno'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalAulaIdRouteImport } from './routes/portal.aula.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAlunoRoute = LoginAlunoRouteImport.update({
  id: '/login/aluno',
  path: '/login/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAulaIdRoute = PortalAulaIdRouteImport.update({
  id: '/aula/$id',
  path: '/aula/$id',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/login/admin': typeof LoginAdminRoute
  '/login/aluno': typeof LoginAlunoRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/aula/$id': typeof PortalAulaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/aluno': typeof LoginAlunoRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/aula/$id': typeof PortalAulaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/login/admin': typeof LoginAdminRoute
  '/login/aluno': typeof LoginAlunoRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/aula/$id': typeof PortalAulaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/portal'
    | '/login/admin'
    | '/login/aluno'
    | '/admin/'
    | '/portal/'
    | '/portal/aula/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login/admin'
    | '/login/aluno'
    | '/admin'
    | '/portal'
    | '/portal/aula/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/portal'
    | '/login/admin'
    | '/login/aluno'
    | '/admin/'
    | '/portal/'
    | '/portal/aula/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  LoginAdminRoute: typeof LoginAdminRoute
  LoginAlunoRoute: typeof LoginAlunoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/aluno': {
      id: '/login/aluno'
      path: '/login/aluno'
      fullPath: '/login/aluno'
      preLoaderRoute: typeof LoginAlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/aula/$id': {
      id: '/portal/aula/$id'
      path: '/aula/$id'
      fullPath: '/portal/aula/$id'
      preLoaderRoute: typeof PortalAulaIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
  PortalAulaIdRoute: typeof PortalAulaIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
  PortalAulaIdRoute: PortalAulaIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  LoginAdminRoute: LoginAdminRoute,
  LoginAlunoRoute: LoginAlunoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
